#!/usr/bin/env bash 
# Displays a list of currently running processes.
# Also shows all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format
# Shows process hierarchy

ps -auxf
