#!/usr/bin/env bash
# change local host to 127.0.0.2
# chaange facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/host.new
cp -f ~/hosts.new /etc/hosts